[package]
name = "weather-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
clap = { version = "3.1.8", features = ["derive"] }
confy = "0.4.0"
reqwest = {version = "0.11.10", features = ["json"]}
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.79"
tokio = {version = "1", features = ["full"]}

